#!/bin/bash
#任何命令执行出错既退出
set -e

#脚本路径
shell_path="$( cd "$( dirname "$0"  )" && pwd  )"
cd ${shell_path}

configPlist_path="${shell_path}/ShellConfig.plist"
entrancePath=`/usr/libexec/PlistBuddy -c "print :entrancePath" $configPlist_path`
codePath=`/usr/libexec/PlistBuddy -c "print :codePath" $configPlist_path`
pack_path=${shell_path}/pack

if [[ -d ${pack_path} ]]; then  
    rm -rf ${pack_path}
fi
mkdir ${pack_path}

newcode_path="${pack_path}/code"
new_script="${pack_path}/script"
echo "\033[32m ------------------$(date "+%H:%M:%S")开始拷贝------------------ \033[0m"
cp -r "${codePath}" "${newcode_path}/"
rsync -r "${entrancePath}" "${new_script}/" --exclude "start"
echo "\033[32m ------------------$(date "+%H:%M:%S")拷贝完成------------------ \033[0m"
echo
echo "\033[32m -----------------开始执行脚本---------------- \033[0m"
sh ${new_script}/entrance.sh "${configPlist_path}" "${newcode_path}/"

#退出命令执行出错既退出模式
set +e
